backend:
  name: github
  repo: anwarmhejazy-afk/dizzypumpkinart-site
  branch: decap-cms-test

media_folder: "images/uploads"
public_folder: "images/uploads"

collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - file: "content/home.json"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Text", name: "hero_text", widget: "text" }